### Create a new admin
POST {{host}}/api/v1/auth/new
Content-Type: application/json
Authorization: Bearer {{auth}}

{
  "loginId": "admin",
  "pwd": "admin",
  "name": "admin"
}

### Login
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
  "userId": "admin",
  "password": "admin"
}

### Get all users
GET {{host}}/api/v1/user
Content-Type: application/json
Authorization: Bearer {{auth}}

### Create a new user
POST {{host}}/api/v1/user/new
Content-Type: application/json
Authorization: Bearer {{auth}}

{
  "name": "김민지",
  "sex": "f",
  "nickname": "뉴진스민지",
  "id": "new.minji",
  "pwd": "000000",
  "teamName": "13조",
  "dob": "2004-05-07",
  "geo": "강원 춘천"
}

### Reset user password
PUT {{host}}/api/v1/user/7549143a-82bb-4dea-804a-096337cacf6f/pwd
Content-Type: application/json
Authorization: Bearer {{auth}}

{
  "newPwd": "000000"
}

### Update user status
PUT {{host}}/api/v1/user/774fcd96-0871-4b17-a104-62f884227d24/block
Content-Type: application/json
Authorization: Bearer {{auth}}

{
  "level": 0
}

### Get team info
GET {{host}}/api/v1/user/team/1
Content-Type: application/json
Authorization: Bearer {{auth}}

### Update team leader
PUT {{host}}/api/v1/user/team/1/leader
Content-Type: application/json
Authorization: Bearer {{auth}}

{
  "userRef": "774fcd96-0871-4b17-a104-62f884227d24"
}

### Create a new group
POST {{host}}/api/v1/group/new?must=true
Content-Type: application/json
Authorization: Bearer {{auth}}

{
  "creatorRef": "774fcd96-0871-4b17-a104-62f884227d24",
  "groupName": "group-3"
}

### list all groups
GET {{host}}/api/v1/group
Content-Type: application/json
Authorization: Bearer {{auth}}

### delete a group
DELETE {{host}}/api/v1/group/1a017a21-b483-44fa-8ad4-4dca1d47528a
Content-Type: application/json
Authorization: Bearer {{auth}}

{}

### list all posts
GET {{host}}/api/v1/post?group-ref=1a017a21-b483-44fa-8ad4-4dca1d47528a
Content-Type: application/json
Authorization: Bearer {{auth}}

### delete a post
DELETE {{host}}/api/v1/post/1
Content-Type: application/json
Authorization: Bearer {{auth}}

{}

