steps:
  # pull secrets
  - name: 'gcr.io/cloud-builders/gsutil'
    args: [ 'cp', '-r','gs://${_MY_BUCKET}/kysa24-admin-api/*', '.' ]
  # build
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/kysa24-sns/kysa24-admin-api', '-f', './build/gcp/Dockerfile', '.' ]
  # push
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/kysa24-sns/kysa24-admin-api' ]
  # deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [ 'run', 'deploy', 'kysa24-admin-api', '--image', 'gcr.io/kysa24-sns/kysa24-admin-api', '--region', 'asia-northeast3', '--port', '3000' ]
images:
  - 'gcr.io/kysa24-sns/kysa24-admin-api'
